# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

# fib code from http://stackoverflow.com/a/24438837
def fib(n, cache = {})
  if n == 0 || n == 1
    return n
  end
  cache[n] ||= fib(n-1, cache) + fib(n-2, cache)
end

# just tested it, 34th fibonacci number > 4 million
puts (1..33).to_a
  .map { |n| fib n }
  .select { |n| n.even? }
  .inject(:+)
